import dash

from dash import dcc
from dash import html
from style import CONTENT_STYLE
from style import NESTA_COLOURS
from style import SIDEBAR_STYLE


dash.register_page(__name__, path="/")

layout = html.Div(
    [
        html.H2("Welcome!", className="display-6"),
        html.P("We have created this app to allow you to explore the data from the QualAF interview transcripts."),
        html.H2("How to use this app", className="display-6"),
        html.H3("Topic overview", className="display-8"),
        dcc.Markdown(
            """
                     This tab gives you some high level information about the different topics.

                     The plots at the top tell you:
                     * the number of different user responses within each topic
                     * the distribution of sentiments within each topic (most will be neutral). This was calculated by applying a
                     sentiment analysis model to each response. See below for more information about this.
                     * The number of different users who appear in each topic. Bear in mind that any one user may have said things that relate to multiple topics,
                     which is why the greatest possible number of users in a topic is 100 as that is the total number of interviews, but the overall numbers in this plot add up to much more than 100!

                     The table at the bottom lists:
                     * The name of each topic (generated by llama3.2)
                     * A description of the topic (also generated by llama3.2)
                     * Key words in the topic - these occurred frequently in this topic, and less frequently in other topics
                     * The number of user responses in the topic (the same information that you can see in the first bar chart)
                     """
        ),
        html.H3("User response mapping", className="display-8"),
        dcc.Markdown(
            """
                     This tab contains an interactive visualisation to help you explore user responses within each topic.

                    The scatterplot shows each user response as a point. **The x and y axes are abstract and do not have any meaning**,
                    though points that are closer together should be similar semantically and points that are further away are more different
                    from each other semantically. Each point on the plot is coloured by topic.

                    You can click topics in the legend to remove them from the plot. For example, the topic 'None' contains responses
                    that could not be assigned to a topic, so you may choose not to display these.

                    You can click a point to find out more information about it. On the left, you will see information about the topic it is in,
                    the ID of the conversation it occurred in, and the response itself.

                    When you click a point from the plot, the table at the bottom of the tab will display the full conversation between
                    BOT and USER (*minus the preamble at the beginning, where the user is asked if they understand the instructions). The response
                    you clicked in the plot will be highlighted in yellow.
                     """
        ),
        html.H2("Methods", className="display-6"),
        dcc.Markdown(
            """
                     ### Text preprocessing
                     * We did some cleaning of the text, for example, grouping together responses that were sent immediately after one another.
                     * Currently, **user responses shorter than 9 words are excluded from the topic modelling** and consequently are not shown in
                     the scatterplot on the 'User response mapping' page. However, all user responses are still included in the table at the bottom of
                     that page.

                     ### Sentiment analysis
                     We used the model [cardiffnlp/twitter-roberta-base-sentiment-latest](https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment-latest)
                     to predict the sentiment of each response. This model has been trained on lots of data (~124 million tweets) and uses the "knowledge" it
                     has "learned" about that data to make predictions about new data that we show it. It categorises texts as "Positive", "Negative", or "Neutral".

                     **We have not yet evaluated its performance
                     on our data**, and so the sentiment predictions should be taken with a pinch of salt.

                     ### Topic modelling
                     We used the popular library [BERTopic](https://maartengr.github.io/BERTopic/api/bertopic.html#bertopic._bertopic.BERTopic.get_representative_docs) to
                     extract topics from the data.

                     This method works by:
                     * Embedding the text data - this means translating the text into a numerical representation (vectors) that a computer can understand.
                     * Applying a clustering algorithm to the vectors. This works to group together similar vectors (and therefore similar text) into clusters.
                     * Extracting the key words that distinguish each cluster from the others.

                     We then also used an LLM (llama3.2) to give each cluster a name and description.
                     """
        ),
    ],
    style=CONTENT_STYLE,
)
